include Makefile.common

PREFIX=$(GCC_ROOT)/bin/msp430-elf-
CC=$(PREFIX)gcc
AR=$(PREFIX)ar

CFLAGS += \
	-mmcu=msp430fr5969 \
	-D__MSP430FR5969__ \
	-DMEMENTOS_FRAM \
	-g \
	-O0 \
	-I$(MEMENTOS_ROOT)/include \
	-I$(GCC_ROOT)/include \

.DUMMY: all
all: libdino.a

%.s: %.c
	$(CC) $(CFLAGS) -S -o $@ $^

%.c: include/mementos.h

libdino.a: dino.o 
	$(AR) r $@ $^

clean:
	$(RM) libdino.a *.o
