#annoyingly, can't include .dino first, but .edb needs this

# override the defualt setting in root makefile

override TOOLCHAIN = clang
override TOOL = dino

DINO_MODE = manual

include ../Makefile

include $(LIB_ROOT)/dino/Makefile.target
