#annoyingly, can't include .dino first, but .edb needs this

# override the defualt setting in root makefile

override TOOLCHAIN = clang

DINO_MODE = auto

include ../Makefile

include $(LIB_ROOT)/dino/Makefile.target


