#annoyingly, can't include .dino first, but .edb needs this

# override the defualt setting in root makefile

override TOOLCHAIN = clang
override TOOL = chain

include ../Makefile

include $(LIB_ROOT)/chain/Makefile.target
